### ISSUE TITLE
Test the checklist

### ISSUE THREAD

**Issue by jacobfike** [jacobfike/Battlebook-API#2]
In order to contribute, you must meet these requirements:
- [x] Don't be an idjut
- [ ] Do follow the code style
- [ ] Don't dring the kool-aid
